<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE groups [

<!ELEMENT groups (group*)>
<!ELEMENT group (searchable-attributes)>
<!ELEMENT searchable-attributes (searchable-attribute+)>
<!ELEMENT searchable-attribute EMPTY>

<!ATTLIST group
	id CDATA #REQUIRED
	userLabel CDATA #REQUIRED>

<!ATTLIST searchable-attribute
	id CDATA #REQUIRED>

]>

<groups>
	<group id="experience" userLabel="Experience">
		<searchable-attributes>
			<searchable-attribute id="yearam"/>
			<searchable-attribute id="voyageId"/>
			<searchable-attribute id="shipname"/>
			<searchable-attribute id="sladvoy"/>
			<searchable-attribute id="slaarriv"/>
			<searchable-attribute id="slas32"/>
			<searchable-attribute id="slas36"/>
			<searchable-attribute id="slas39"/>
			<searchable-attribute id="ncar13"/>
			<searchable-attribute id="ncar15"/>
			<searchable-attribute id="ncar17"/>
			<searchable-attribute id="vymrtimp"/>
			<searchable-attribute id="womrat7"/>
			<searchable-attribute id="girlrat7"/>
			<searchable-attribute id="boyrat7"/>
			<searchable-attribute id="jamcaspr"/>
			<searchable-attribute id="adpsale1"/>
			<searchable-attribute id="adpsale2"/>
			<searchable-attribute id="crew1"/>
			<searchable-attribute id="crew3"/>
			<searchable-attribute id="crewdied"/>
			<searchable-attribute id="d1slatr"/>
			<searchable-attribute id="ddepamb"/>
			<searchable-attribute id="fate"/>
			<searchable-attribute id="fate2"/>
			<searchable-attribute id="insurrec"/>
			<searchable-attribute id="malrat7"/>
			<searchable-attribute id="sla32imp"/>
			<searchable-attribute id="sla36imp"/>
			<searchable-attribute id="sla39imp"/>
			<searchable-attribute id="slamimp"/>
			<searchable-attribute id="slaximp"/>
			<searchable-attribute id="timslave"/>
			<searchable-attribute id="voy2imp"/>
			<searchable-attribute id="vymrtrat"/>
			<searchable-attribute id="ncr15imp"/>
			<searchable-attribute id="rountrip"/>
			<searchable-attribute id="datarr4"/>
			<searchable-attribute id="datarr32"/>
			<searchable-attribute id="datarr33"/>
			<searchable-attribute id="ncr17imp"/>
		</searchable-attributes>
	</group>
	<group id="geography" userLabel="Geography">
		<searchable-attributes>
			<searchable-attribute id="yearam"/>
			<searchable-attribute id="voyageId"/>
			<searchable-attribute id="shipname"/>
			<searchable-attribute id="arrport"/>
			<searchable-attribute id="embport"/>
			<searchable-attribute id="regem1"/>
			<searchable-attribute id="regem2"/>
			<searchable-attribute id="regem3"/>
			<searchable-attribute id="majbuyrg"/>
			<searchable-attribute id="regdis2"/>
			<searchable-attribute id="regdis3"/>
			<searchable-attribute id="majselrg"/>
			<searchable-attribute id="xmimpflag"/>
			<searchable-attribute id="adpsale1"/>
			<searchable-attribute id="adpsale2"/>
			<searchable-attribute id="deptreg"/>
			<searchable-attribute id="majselpt"/>
			<searchable-attribute id="majbyimp"/>
			<searchable-attribute id="mjselimp"/>
			<searchable-attribute id="regdis1"/>
			<searchable-attribute id="sla1port"/>
			<searchable-attribute id="majbuypt"/>
			<searchable-attribute id="plac1tra"/>
			<searchable-attribute id="plac2tra"/>
			<searchable-attribute id="plac3tra"/>
			<searchable-attribute id="portdep"/>
			<searchable-attribute id="portret"/>
		</searchable-attributes>
	</group>
	<group id="ship" userLabel="Ship">
		<searchable-attributes>
			<searchable-attribute id="yearam"/>
			<searchable-attribute id="voyageId"/>
			<searchable-attribute id="natinimp"/>
			<searchable-attribute id="shipname"/>
			<searchable-attribute id="rig"/>
			<searchable-attribute id="tonnage"/>
			<searchable-attribute id="guns"/>
			<searchable-attribute id="placcons"/>
			<searchable-attribute id="tonmod"/>
			<searchable-attribute id="evgreen"/>
			<searchable-attribute id="xmimpflag"/>
			<searchable-attribute id="datedep"/>
			<searchable-attribute id="fate"/>
			<searchable-attribute id="fate4"/>
			<searchable-attribute id="timslave"/>
			<searchable-attribute id="rountrip"/>
			<searchable-attribute id="captaina"/>
			<searchable-attribute id="captainb"/>
			<searchable-attribute id="captainc"/>
			<searchable-attribute id="ownera"/>
			<searchable-attribute id="ownerf"/>
			<searchable-attribute id="ownerb"/>
			<searchable-attribute id="ownerc"/>
			<searchable-attribute id="ownerd"/>
			<searchable-attribute id="ownere"/>
			<searchable-attribute id="ownerg"/>
			<searchable-attribute id="ownerh"/>
			<searchable-attribute id="owneri"/>
			<searchable-attribute id="ownerj"/>
			<searchable-attribute id="ownerk"/>
			<searchable-attribute id="ownerl"/>
			<searchable-attribute id="ownerm"/>
			<searchable-attribute id="ownern"/>
			<searchable-attribute id="ownero"/>
			<searchable-attribute id="ownerp"/>
			<searchable-attribute id="datarr4"/>
			<searchable-attribute id="fate3"/>
			<searchable-attribute id="portdep"/>
			<searchable-attribute id="portret"/>
			<searchable-attribute id="anycaptain"/>
			<searchable-attribute id="anyowner"/>
		</searchable-attributes>
	</group>
	<group id="personnel" userLabel="Ship Personnel">
		<searchable-attributes>
			<searchable-attribute id="yearam"/>
			<searchable-attribute id="voyageId"/>
			<searchable-attribute id="shipname"/>
			<searchable-attribute id="crew1"/>
			<searchable-attribute id="crew3"/>
			<searchable-attribute id="crewdied"/>
			<searchable-attribute id="timslave"/>
			<searchable-attribute id="rountrip"/>
			<searchable-attribute id="portdep"/>
			<searchable-attribute id="portret"/>
			<searchable-attribute id="anycaptain"/>
			<searchable-attribute id="anyowner"/>
		</searchable-attributes>
	</group>
	<group id="slaves" userLabel="Slaves">
		<searchable-attributes>
			<searchable-attribute id="yearam"/>
			<searchable-attribute id="voyageId"/>
			<searchable-attribute id="shipname"/>
			<searchable-attribute id="tslavesd"/>
			<searchable-attribute id="sladvoy"/>
			<searchable-attribute id="slaarriv"/>
			<searchable-attribute id="slas32"/>
			<searchable-attribute id="slas36"/>
			<searchable-attribute id="slas39"/>
			<searchable-attribute id="slintend"/>
			<searchable-attribute id="ncar13"/>
			<searchable-attribute id="ncar15"/>
			<searchable-attribute id="ncar17"/>
			<searchable-attribute id="vymrtimp"/>
			<searchable-attribute id="regem1"/>
			<searchable-attribute id="regem2"/>
			<searchable-attribute id="regem3"/>
			<searchable-attribute id="majbuyrg"/>
			<searchable-attribute id="regdis2"/>
			<searchable-attribute id="regdis3"/>
			<searchable-attribute id="majselrg"/>
			<searchable-attribute id="price"/>
			<searchable-attribute id="womrat7"/>
			<searchable-attribute id="menrat7"/>
			<searchable-attribute id="girlrat7"/>
			<searchable-attribute id="boyrat7"/>
			<searchable-attribute id="jamcaspr"/>
			<searchable-attribute id="adpsale1"/>
			<searchable-attribute id="adpsale2"/>
			<searchable-attribute id="chilrat7"/>
			<searchable-attribute id="d1slatr"/>
			<searchable-attribute id="ddepamb"/>
			<searchable-attribute id="fate"/>
			<searchable-attribute id="fate2"/>
			<searchable-attribute id="insurrec"/>
			<searchable-attribute id="majselpt"/>
			<searchable-attribute id="malrat7"/>
			<searchable-attribute id="majbyimp"/>
			<searchable-attribute id="mjselimp"/>
			<searchable-attribute id="regdis1"/>
			<searchable-attribute id="sla1port"/>
			<searchable-attribute id="sla32imp"/>
			<searchable-attribute id="sla36imp"/>
			<searchable-attribute id="sla39imp"/>
			<searchable-attribute id="slamimp"/>
			<searchable-attribute id="slaximp"/>
			<searchable-attribute id="vymrtrat"/>
			<searchable-attribute id="ncr15imp"/>
			<searchable-attribute id="datarr32"/>
			<searchable-attribute id="datarr33"/>
			<searchable-attribute id="majbuypt"/>
			<searchable-attribute id="ncr17imp"/>
			<searchable-attribute id="plac1tra"/>
			<searchable-attribute id="plac2tra"/>
			<searchable-attribute id="plac3tra"/>
		</searchable-attributes>
	</group>
	<group id="sources" userLabel="Sources">
		<searchable-attributes>
			<searchable-attribute id="yearam"/>
			<searchable-attribute id="voyageId"/>
			<searchable-attribute id="shipname"/>
			<searchable-attribute id="sourceg"/>
			<searchable-attribute id="sourceh"/>
			<searchable-attribute id="sourcei"/>
			<searchable-attribute id="sourcej"/>
			<searchable-attribute id="sourcek"/>
			<searchable-attribute id="sourcel"/>
			<searchable-attribute id="sourcem"/>
			<searchable-attribute id="sourcen"/>
			<searchable-attribute id="sourceo"/>
			<searchable-attribute id="sourcep"/>
			<searchable-attribute id="sourceq"/>
			<searchable-attribute id="sourcer"/>
			<searchable-attribute id="sourcea"/>
			<searchable-attribute id="sourceb"/>
			<searchable-attribute id="sourcec"/>
			<searchable-attribute id="sourced"/>
			<searchable-attribute id="sourcee"/>
			<searchable-attribute id="sourcef"/>
		</searchable-attributes>
	</group>
</groups>