<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE searchable-attributes [

<!ELEMENT searchable-attributes (searchable-attribute*)>
<!ELEMENT searchable-attribute ((attributes|locations))>
<!ELEMENT attributes (attribute+)>
<!ELEMENT locations (location+)>
<!ELEMENT attribute EMPTY>
<!ELEMENT location EMPTY>

<!ATTLIST searchable-attribute
	id CDATA #REQUIRED
	userLabel CDATA #REQUIRED
	type CDATA #REQUIRED
	userCategory (beginners|general) #REQUIRED>

<!ATTLIST attribute name CDATA #REQUIRED>

<!ATTLIST location
	port CDATA #REQUIRED
	region CDATA #REQUIRED>

]>

<searchable-attributes>

	<searchable-attribute
		type="simple"
		id="voyageid"
		userCategory="general"
		userLabel="Voyage identification number">
		<attributes>
			<attribute name="voyageid" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="cd"
		userCategory="general"
		userLabel="Voyage in 1999 CD-ROM">
		<attributes>
			<attribute name="cd" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="shipname"
		userCategory="general"
		userLabel="Name of slave ship">
		<attributes>
			<attribute name="shipname" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="placcons"
		userCategory="general"
		userLabel="Place where ship constructed">
		<attributes>
			<attribute name="placcons" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="yrcons"
		userCategory="general"
		userLabel="Year of ship construction">
		<attributes>
			<attribute name="yrcons" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="placreg"
		userCategory="general"
		userLabel="Place where ship registered">
		<attributes>
			<attribute name="placreg" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="yrreg"
		userCategory="general"
		userLabel="Year of ship registration">
		<attributes>
			<attribute name="yrreg" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="natinimp"
		userCategory="general"
		userLabel="Imputed national registration">
		<attributes>
			<attribute name="natinimp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="rig"
		userCategory="general"
		userLabel="Rig of ship">
		<attributes>
			<attribute name="rig" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="tonnage"
		userCategory="general"
		userLabel="Tonnage of ship">
		<attributes>
			<attribute name="tonnage" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="tonmod"
		userCategory="general"
		userLabel="Standardized tonnage">
		<attributes>
			<attribute name="tonmod" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="guns"
		userCategory="general"
		userLabel="Number of guns carried">
		<attributes>
			<attribute name="guns" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="anyowner"
		userCategory="general"
		userLabel="An owner">
		<attributes>
			<attribute name="ownera" />
			<attribute name="ownerf" />
			<attribute name="ownerb" />
			<attribute name="ownerc" />
			<attribute name="ownerd" />
			<attribute name="ownere" />
			<attribute name="ownerg" />
			<attribute name="ownerh" />
			<attribute name="owneri" />
			<attribute name="ownerj" />
			<attribute name="ownerk" />
			<attribute name="ownerl" />
			<attribute name="ownerm" />
			<attribute name="ownern" />
			<attribute name="ownero" />
			<attribute name="ownerp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="fate"
		userCategory="general"
		userLabel="Outcome of voyage">
		<attributes>
			<attribute name="fate" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="fate2"
		userCategory="general"
		userLabel="Outcome of voyage for slaves">
		<attributes>
			<attribute name="fate2" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="fate4"
		userCategory="general"
		userLabel="Outcome of voyage for owner">
		<attributes>
			<attribute name="fate4" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="fate3"
		userCategory="general"
		userLabel="Outcome of voyage if ship captured">
		<attributes>
			<attribute name="fate3" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="resistance"
		userCategory="general"
		userLabel="Violent incidents">
		<attributes>
			<attribute name="resistance" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="portdep"
		userCategory="general"
		userLabel="Port where voyage began">
		<attributes>
			<attribute name="portdep" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="ptdepimp"
		userCategory="general"
		userLabel="Imputed port where voyage began">
		<attributes>
			<attribute name="ptdepimp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="deptregimp"
		userCategory="general"
		userLabel="Imputed region where voyage began">
		<attributes>
			<attribute name="deptregimp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="plac1tra"
		userCategory="general"
		userLabel="First place of slave purchase">
		<attributes>
			<attribute name="plac1tra" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="plac2tra"
		userCategory="general"
		userLabel="Second place of slave purchase">
		<attributes>
			<attribute name="plac2tra" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="plac3tra"
		userCategory="general"
		userLabel="Third place of slave purchase">
		<attributes>
			<attribute name="plac3tra" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="mjbyptimp"
		userCategory="general"
		userLabel="Imputed principal place of slave putchase">
		<attributes>
			<attribute name="mjbyptimp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="regem1"
		userCategory="general"
		userLabel="First region of slave purchase">
		<attributes>
			<attribute name="regem1" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="regem2"
		userCategory="general"
		userLabel="Second region of slave purchase">
		<attributes>
			<attribute name="regem2" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="regem3"
		userCategory="general"
		userLabel="Third region of slave purchase">
		<attributes>
			<attribute name="regem3" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="majbyimp"
		userCategory="general"
		userLabel="Imputed principal region of slave purchase">
		<attributes>
			<attribute name="majbyimp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="npafttra"
		userCategory="general"
		userLabel="Places of call before Atlantic crossing">
		<attributes>
			<attribute name="npafttra" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="sla1port"
		userCategory="general"
		userLabel="First place of landing">
		<attributes>
			<attribute name="sla1port" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="adpsale1"
		userCategory="general"
		userLabel="Second place of landing">
		<attributes>
			<attribute name="adpsale1" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="adpsale2"
		userCategory="general"
		userLabel="Third place of landing">
		<attributes>
			<attribute name="adpsale2" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="mjslptimp"
		userCategory="general"
		userLabel="Imputed principal place of landing">
		<attributes>
			<attribute name="mjslptimp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="regdis1"
		userCategory="general"
		userLabel="First region of disembarkation">
		<attributes>
			<attribute name="regdis1" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="regdis2"
		userCategory="general"
		userLabel="Second region of disembarkation">
		<attributes>
			<attribute name="regdis2" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="regdis3"
		userCategory="general"
		userLabel="Third region of disembarkation">
		<attributes>
			<attribute name="regdis3" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="mjselimp"
		userCategory="general"
		userLabel="Imputed principal region of disembarkation">
		<attributes>
			<attribute name="mjselimp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="portret"
		userCategory="general"
		userLabel="Port at which voyage ended">
		<attributes>
			<attribute name="portret" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="retrnreg"
		userCategory="general"
		userLabel="Region to which ship returned">
		<attributes>
			<attribute name="retrnreg" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="yearam"
		userCategory="general"
		userLabel="Imputed year of arrival at first place of landing">
		<attributes>
			<attribute name="yearam" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="datedep"
		userCategory="general"
		userLabel="Date that voyage began">
		<attributes>
			<attribute name="Date_dep" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="datebuy"
		userCategory="general"
		userLabel="Date that slave purchase began">
		<attributes>
			<attribute name="Date_buy" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="dateleftAfr"
		userCategory="general"
		userLabel="Date that vessel left last slaving port">
		<attributes>
			<attribute name="Date_leftAfr" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="dateland1"
		userCategory="general"
		userLabel="Date that slaves landed at first place">
		<attributes>
			<attribute name="Date_land1" />
		</attributes>
	</searchable-attribute>
	
	<searchable-attribute
		type="simple"
		id="dateland2"
		userCategory="general"
		userLabel="Date of arrival at second place of landing">
		<attributes>
			<attribute name="Date_land2" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="dateland3"
		userCategory="general"
		userLabel="Date that slaves landed at third place">
		<attributes>
			<attribute name="Date_land3" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="datedepam"
		userCategory="general"
		userLabel="Date that ship left on return voyage">
		<attributes>
			<attribute name="Date_depam" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="dateend"
		userCategory="general"
		userLabel="Date when voyage completed">
		<attributes>
			<attribute name="Date_end" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="voy1imp"
		userCategory="general"
		userLabel="Imputed voyage length from departure to first port of landing">
		<attributes>
			<attribute name="voy1imp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="voy2imp"
		userCategory="general"
		userLabel="Imputed length of middle passage">
		<attributes>
			<attribute name="voy2imp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="voy3imp"
		userCategory="general"
		userLabel="Imputed voyage length from departure to return to home port">
		<attributes>
			<attribute name="voy3imp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="anycaptain"
		userCategory="general"
		userLabel="Name(s) of captain(s)">
		<attributes>
			<attribute name="captaina" />
			<attribute name="captainb" />
			<attribute name="captainc" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="crew1"
		userCategory="general"
		userLabel="Crew on board at outset of voyage">
		<attributes>
			<attribute name="crew1" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="crew3"
		userCategory="general"
		userLabel="Number of crew when first slaves landed">
		<attributes>
			<attribute name="crew3" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="crewdied"
		userCategory="general"
		userLabel="Number of crew who died over entire voyage">
		<attributes>
			<attribute name="crewdied" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="slintend"
		userCategory="general"
		userLabel="Number of slaves intended at first place of purchase">
		<attributes>
			<attribute name="slintend" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="ncar13"
		userCategory="general"
		userLabel="Slaves carried from first port of purchase">
		<attributes>
			<attribute name="ncar13" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="ncar15"
		userCategory="general"
		userLabel="Slaves carried from second port of purchase">
		<attributes>
			<attribute name="ncar15" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="ncar17"
		userCategory="general"
		userLabel="Slaves carried from third port of purchase">
		<attributes>
			<attribute name="ncar17" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="tslavesd"
		userCategory="general"
		userLabel="Total slaves carried off from Africa">
		<attributes>
			<attribute name="tslavesd" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="slaarriv"
		userCategory="general"
		userLabel="Number of slaves who arrived at first place of landing">
		<attributes>
			<attribute name="slaarriv" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="slas32"
		userCategory="general"
		userLabel="Number of slaves landed at first place">
		<attributes>
			<attribute name="slas32" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="slas36"
		userCategory="general"
		userLabel="Number of slaves landed at second place">
		<attributes>
			<attribute name="slas36" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="slas39"
		userCategory="general"
		userLabel="Number of slaves landed at third place">
		<attributes>
			<attribute name="slas39" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="slaximp"
		userCategory="general"
		userLabel="Imputed total slaves embarked">
		<attributes>
			<attribute name="slaximp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="slamimp"
		userCategory="general"
		userLabel="Imputed total slaves disembarked">
		<attributes>
			<attribute name="slamimp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="menrat7"
		userCategory="general"
		userLabel="Percentage of men at beginning or end of Middle Passage">
		<attributes>
			<attribute name="menrat7" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="womrat7"
		userCategory="general"
		userLabel="Percentage of women at beginning or end of Middle Passage">
		<attributes>
			<attribute name="womrat7" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="boyrat7"
		userCategory="general"
		userLabel="Percentage of boys at beginning or end of Middle Passage">
		<attributes>
			<attribute name="boyrat7" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="girlrat7"
		userCategory="general"
		userLabel="Percentage of girls at beginning or end of Middle Passage">
		<attributes>
			<attribute name="girlrat7" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="malrat7"
		userCategory="general"
		userLabel="Imputed sex ratio of the cargo of slaves">
		<attributes>
			<attribute name="malrat7" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="chilrat7"
		userCategory="general"
		userLabel="Imputed ratio of children to adults in the cargo of slaves">
		<attributes>
			<attribute name="chilrat7" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="jamcaspr"
		userCategory="general"
		userLabel="Imputed sterling price of slaves sold in Jamaica">
		<attributes>
			<attribute name="jamcaspr" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="vymrtimp"
		userCategory="general"
		userLabel="Imputed number of slaves who died during the Middle Passage">
		<attributes>
			<attribute name="vymrtimp" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="vymrtrat"
		userCategory="general"
		userLabel="Imputed mortality rate (slave deaths / embarkations)">
		<attributes>
			<attribute name="vymrtrat" />
		</attributes>
	</searchable-attribute>

	<searchable-attribute
		type="simple"
		id="anysource"
		userCategory="general"
		userLabel="Source">
		<attributes>
			<attribute name="sourceg" />
			<attribute name="sourceh" />
			<attribute name="sourcei" />
			<attribute name="sourcej" />
			<attribute name="sourcek" />
			<attribute name="sourcel" />
			<attribute name="sourcem" />
			<attribute name="sourcen" />
			<attribute name="sourceo" />
			<attribute name="sourcep" />
			<attribute name="sourceq" />
			<attribute name="sourcer" />
			<attribute name="sourcea" />
			<attribute name="sourceb" />
			<attribute name="sourcec" />
			<attribute name="sourced" />
			<attribute name="sourcee" />
			<attribute name="sourcef" />
			<attribute name="sourcex" />
		</attributes>
	</searchable-attribute>

</searchable-attributes>
